.PHONY: clean All

All:
	@echo "----------Building project:[ Graham_scan - Debug ]----------"
	@cd "Graham_scan" && "$(MAKE)" -f  "Graham_scan.mk"
clean:
	@echo "----------Cleaning project:[ Graham_scan - Debug ]----------"
	@cd "Graham_scan" && "$(MAKE)" -f  "Graham_scan.mk" clean
